// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package biedaprint

import (
	"fmt"
	"io"
	"strconv"
	"time"
)

type GcodeFileMeta struct {
	OriginalName   string             `json:"originalName"`
	GcodeFileName  string             `json:"gcodeFileName"`
	UploadDate     time.Time          `json:"uploadDate"`
	TotalLines     int                `json:"totalLines"`
	PrintTime      float64            `json:"printTime"`
	FilamentUsedMm float64            `json:"filamentUsedMm"`
	LayerIndexes   []*GcodeLayerIndex `json:"layerIndexes"`
}

type GcodeLayerIndex struct {
	LineNumber  int `json:"lineNumber"`
	LayerNumber int `json:"layerNumber"`
}

type NewSettings struct {
	SerialPort           string `json:"serialPort"`
	BaudRate             int    `json:"baudRate"`
	ScrollbackBufferSize int    `json:"scrollbackBufferSize"`
	DataPath             string `json:"dataPath"`
	StartupCommand       string `json:"startupCommand"`
}

type PrintJob struct {
	GcodeMeta   *GcodeFileMeta `json:"gcodeMeta"`
	StartedTime time.Time      `json:"startedTime"`
}

type Settings struct {
	SerialPort           string `json:"serialPort"`
	BaudRate             int    `json:"baudRate"`
	ScrollbackBufferSize int    `json:"scrollbackBufferSize"`
	DataPath             string `json:"dataPath"`
	StartupCommand       string `json:"startupCommand"`
}

type TrackedValue struct {
	Name              string                  `json:"name"`
	Unit              string                  `json:"unit"`
	DisplayType       TrackedValueDisplayType `json:"displayType"`
	PlotColor         string                  `json:"plotColor"`
	Value             interface{}             `json:"value"`
	LastUpdate        *time.Time              `json:"lastUpdate"`
	LastSent          *time.Time              `json:"lastSent"`
	MinUpdateInterval int                     `json:"minUpdateInterval"`
	History           []interface{}           `json:"history"`
	MaxHistoryLength  int                     `json:"maxHistoryLength"`
}

type TrackedValueDisplayType string

const (
	TrackedValueDisplayTypePlot    TrackedValueDisplayType = "PLOT"
	TrackedValueDisplayTypeTime    TrackedValueDisplayType = "TIME"
	TrackedValueDisplayTypeNumber  TrackedValueDisplayType = "NUMBER"
	TrackedValueDisplayTypeBoolean TrackedValueDisplayType = "BOOLEAN"
	TrackedValueDisplayTypeString  TrackedValueDisplayType = "STRING"
)

var AllTrackedValueDisplayType = []TrackedValueDisplayType{
	TrackedValueDisplayTypePlot,
	TrackedValueDisplayTypeTime,
	TrackedValueDisplayTypeNumber,
	TrackedValueDisplayTypeBoolean,
	TrackedValueDisplayTypeString,
}

func (e TrackedValueDisplayType) IsValid() bool {
	switch e {
	case TrackedValueDisplayTypePlot, TrackedValueDisplayTypeTime, TrackedValueDisplayTypeNumber, TrackedValueDisplayTypeBoolean, TrackedValueDisplayTypeString:
		return true
	}
	return false
}

func (e TrackedValueDisplayType) String() string {
	return string(e)
}

func (e *TrackedValueDisplayType) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = TrackedValueDisplayType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid TrackedValueDisplayType", str)
	}
	return nil
}

func (e TrackedValueDisplayType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
