name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      # - name: Get dependencies
      #   run: |
      #     GO111MODULE=off go get -u github.com/99designs/gqlgen
      #     GO111MODULE=off go get -u github.com/gobuffalo/packr/v2/packr2
      #     cd frontend && npm i && cd ..
      - name: Build
        run: |
          cd frontend && npm i && cd ..
          make build-multiplatform
