name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      # - name: Get dependencies
      #   run: |
      #     GO111MODULE=off go get -u github.com/99designs/gqlgen
      #     GO111MODULE=off go get -u github.com/gobuffalo/packr/v2/packr2
      #     cd frontend && npm i && cd ..
      - uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - uses: actions/setup-go@v1
        with:
          go-version: '1.14.1' 
      - name: Install packr2
        run: |
          go build -o /tmp/packr2 github.com/gobuffalo/packr/v2/packr2 
      - name: Frontend npm install
        run: |
          cd frontend && npm i && cd ..
      - name: Install cross-compilers
        run: |
           sudo apt-get update
           sudo apt-get install gcc-arm-linux-gnueabi gcc-aarch64-linux-gnu
      - name: Build
        env:
          PACKR2_PATH: /tmp/packr2
          GITHUB_REF: ${{ github.ref }}
          GOPATH: /home/runner/go
        run: |
          make build-multiplatform
      - uses: actions/upload-artifact@v1
        with:
          name: biedaprint-linux-x86_64
          path: build/
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: build/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}